sinkfile <-function(theWholepage, theFilename){		# "abc def" -> "abc+def"
    htmlTitle = gsub("\\.html", "", theFilename)
    sink(theFilename)
      cat('<base target="_blank"><html><head><title>',htmlTitle,'</title>\n', sep="")
      cat('<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n')
      cat('<meta name="viewport" content="width=device-width, initial-scale=1" />\n')
      cat('<link rel="stylesheet" href="https://williamkpchan.github.io/maincss.css">\n')
      cat('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.js"></script>\n')
      cat('<script src="https://williamkpchan.github.io/lazyload.min.js"></script>\n')
      cat('<script type="text/javascript" src="https://williamkpchan.github.io/mainscript.js"></script>\n')
      cat('<script src="https://williamkpchan.github.io/commonfunctions.js"></script>\n')
      cat('<script src="https://d3js.org/d3.v4.min.js"></script>\n')
      cat('<script>\n')
          cat('  var showTopicNumber = false;\n')
          cat('  var topicEnd = " ";\n')
          cat('  var bookid = "',htmlTitle,'"\n', sep="")
          cat('  var markerName = "img"\n')
      cat('</script>\n')
      cat('<style>\n')
      cat('body{width:100%;margin-left: 0%; font-size:22px;}\n')
      cat('h1, h2 {color: gold;}\n')
      cat('strong {color: orange;}\n')
      cat('pre{width:100%; text-align:center;}\n')
      cat('</style></head><body onkeypress="chkKey()"><center>\n')
      cat('Total: ', length(theWholepage), '<br>\n')
      cat('<div id="toc"></div>\n')
      cat('<center>\n')
      for(i in 1: length(theWholepage)){
        cat(theWholepage[i], sep="\n")
        if(i%%3 ==0){cat("<br>")}
      }
      cat('<script src="https://williamkpchan.github.io/LibDocs/readbook.js"></script>\n<script src="https://williamkpchan.github.io/imgControl.js"></script>\n')
      cat('<script>var lazyLoadInstance= new LazyLoad({elements_selector:".lazy"});</script>\n')

      cat('</body></html>\n')
    sink()
    cat(red("\nJob completed!\n"))
    endTime = format(Sys.time(), "%H:%M")
    cat(cyan("\noutfile file: "), white(theFilename), "\n\n")

    cat("startTime: ", startTime, " endTime: ",endTime,"\n\n")
    shell(theFilename)
}
